"""fixed image_url of shelves

Revision ID: 032f52424a41
Revises: 9e69a045d3b3
Create Date: 2026-06-11 13:27:48.860290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032f52424a41'
down_revision: Union[str, Sequence[str], None] = '9e69a045d3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shelves', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shelves', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
