"""add image_url for authors and shelves

Revision ID: 9e69a045d3b3
Revises: d840333dac96
Create Date: 2026-06-10 20:16:09.744565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e69a045d3b3'
down_revision: Union[str, Sequence[str], None] = 'd840333dac96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('shelves', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shelves', 'image_url')
    op.drop_column('authors', 'image_url')
    # ### end Alembic commands ###
